# Generated by Django 5.2.8 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SoilRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ph", models.FloatField()),
                ("nitrogen", models.FloatField()),
                ("phosphorus", models.FloatField()),
                ("potassium", models.FloatField()),
                ("moisture", models.FloatField()),
                ("organic_carbon", models.FloatField()),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
                ("score", models.IntegerField()),
                ("recommended_crops", models.TextField()),
                ("ai_response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
