# Generated by Django 5.2.8 on 2025-11-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("soil", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="soilrecord",
            name="ai_insight",
            field=models.TextField(blank=True, null=True),
        ),
    ]
